package cn.ctyun.apis;

import cn.ctyun.sdk.CtyunClient;
import cn.ctyun.sdk.Endpoint;

public class Apis {

    public static final String ENDPOINT_NAME = "ctelb";

    public final CtelbElbDisableIDCApi ctelbElbDisableIDCApi;
    public final CtelbElbEnableIDCApi ctelbElbEnableIDCApi;
    public final CtelbGwlbCreateApi ctelbGwlbCreateApi;
    public final CtelbGwlbUpdateApi ctelbGwlbUpdateApi;
    public final CtelbGwlbDeleteApi ctelbGwlbDeleteApi;
    public final CtelbGwlbDisableDeleteProtectionApi ctelbGwlbDisableDeleteProtectionApi;
    public final CtelbGwlbDisableIpv6Api ctelbGwlbDisableIpv6Api;
    public final CtelbGwlbEnableIpv6Api ctelbGwlbEnableIpv6Api;
    public final CtelbGwlbEnableDeleteProtectionApi ctelbGwlbEnableDeleteProtectionApi;
    public final CtelbGwlbShowApi ctelbGwlbShowApi;
    public final CtelbGwlbListApi ctelbGwlbListApi;
    public final CtelbGwlbCreateTargetApi ctelbGwlbCreateTargetApi;
    public final CtelbGwlbUpdateTargetApi ctelbGwlbUpdateTargetApi;
    public final CtelbGwlbDeleteTargetApi ctelbGwlbDeleteTargetApi;
    public final CtelbGwlbShowTargetApi ctelbGwlbShowTargetApi;
    public final CtelbGwlbListTargetApi ctelbGwlbListTargetApi;
    public final CtelbGwlbCreateTargetGroupApi ctelbGwlbCreateTargetGroupApi;
    public final CtelbGwlbUpdateTargetGroupApi ctelbGwlbUpdateTargetGroupApi;
    public final CtelbGwlbDeleteTargetGroupApi ctelbGwlbDeleteTargetGroupApi;
    public final CtelbGwlbShowTargetGroupApi ctelbGwlbShowTargetGroupApi;
    public final CtelbGwlbListTargetGroupApi ctelbGwlbListTargetGroupApi;
    public final CtelbIplistenerCreateApi ctelbIplistenerCreateApi;
    public final CtelbIplistenerUpdateApi ctelbIplistenerUpdateApi;
    public final CtelbIplistenerDeleteApi ctelbIplistenerDeleteApi;
    public final CtelbIplistenerShowApi ctelbIplistenerShowApi;
    public final CtelbIplistenerListApi ctelbIplistenerListApi;
    public final CtelbElbModifyAccessLogApi ctelbElbModifyAccessLogApi;
    public final CtelbElbDeleteAccessLogApi ctelbElbDeleteAccessLogApi;
    public final CtelbElbCreateAccessLogApi ctelbElbCreateAccessLogApi;
    public final CtelbCheckServerCertApi ctelbCheckServerCertApi;
    public final CtelbCheckCaCertApi ctelbCheckCaCertApi;
    public final CtelbListDomainCertLinksApi ctelbListDomainCertLinksApi;
    public final CtelbUpdateDomainCertLinksApi ctelbUpdateDomainCertLinksApi;
    public final CtelbDeleteDomainCertLinksApi ctelbDeleteDomainCertLinksApi;
    public final CtelbCreateDomainCertLinkApi ctelbCreateDomainCertLinkApi;
    public final CtelbRefundPgelbApi ctelbRefundPgelbApi;
    public final CtelbUpdateListenerResponseTimeoutApi ctelbUpdateListenerResponseTimeoutApi;
    public final CtelbUpdateListenerQpsApi ctelbUpdateListenerQpsApi;
    public final CtelbUpdateListenerNat64Api ctelbUpdateListenerNat64Api;
    public final CtelbUpdateListenerIdleTimeoutApi ctelbUpdateListenerIdleTimeoutApi;
    public final CtelbUpdateListenerEstabTimeoutApi ctelbUpdateListenerEstabTimeoutApi;
    public final CtelbUpdateListenerCpsApi ctelbUpdateListenerCpsApi;
    public final CtelbElbUnbindLabelsApi ctelbElbUnbindLabelsApi;
    public final CtelbElbBindLabelsApi ctelbElbBindLabelsApi;
    public final CtelbListElbLabelsApi ctelbListElbLabelsApi;
    public final CtelbUpgradeToPgelbApi ctelbUpgradeToPgelbApi;
    public final CtelbQueryRenewPgelbPriceApi ctelbQueryRenewPgelbPriceApi;
    public final CtelbRenewPgelbApi ctelbRenewPgelbApi;
    public final CtelbQueryModifyPgelbSpecPriceApi ctelbQueryModifyPgelbSpecPriceApi;
    public final CtelbModifyPgelbSpecApi ctelbModifyPgelbSpecApi;
    public final CtelbQueryCreatePgelbPriceApi ctelbQueryCreatePgelbPriceApi;
    public final CtelbCreatePgelbApi ctelbCreatePgelbApi;
    public final CtelbNewQueryElbReatimeMonitorApi ctelbNewQueryElbReatimeMonitorApi;
    public final CtelbNewQueryElbHistoryMonitorApi ctelbNewQueryElbHistoryMonitorApi;
    public final CtelbUpdateVmPoolAttrApi ctelbUpdateVmPoolAttrApi;
    public final CtelbUpdatePolicyAttrApi ctelbUpdatePolicyAttrApi;
    public final CtelbAsyncCreatePolicyApi ctelbAsyncCreatePolicyApi;
    public final CtelbRemoveVmApi ctelbRemoveVmApi;
    public final CtelbListVmApi ctelbListVmApi;
    public final CtelbAsyncCreateTargetApi ctelbAsyncCreateTargetApi;
    public final CtelbUpdateListenerAttrApi ctelbUpdateListenerAttrApi;
    public final CtelbAsyncCreateListenerApi ctelbAsyncCreateListenerApi;
    public final CtelbListVmPoolApi ctelbListVmPoolApi;
    public final CtelbAsyncCreateCertificateApi ctelbAsyncCreateCertificateApi;
    public final CtelbAsyncCreateLoadbalanceApi ctelbAsyncCreateLoadbalanceApi;
    public final CtelbQueryElbHistoryMetricApi ctelbQueryElbHistoryMetricApi;
    public final CtelbUpdateCertificateApi ctelbUpdateCertificateApi;
    public final CtelbEnableElbIpv6Api ctelbEnableElbIpv6Api;
    public final CtelbDisableElbIpv6Api ctelbDisableElbIpv6Api;
    public final CtelbShowAccessControlApi ctelbShowAccessControlApi;
    public final CtelbShowHealthCheckApi ctelbShowHealthCheckApi;
    public final CtelbQueryElbReatimeMetricApi ctelbQueryElbReatimeMetricApi;
    public final CtelbQuerySlaApi ctelbQuerySlaApi;
    public final CtelbListQueryApi ctelbListQueryApi;
    public final CtelbShowRuleApi ctelbShowRuleApi;
    public final CtelbUpdateRuleApi ctelbUpdateRuleApi;
    public final CtelbDeleteRuleApi ctelbDeleteRuleApi;
    public final CtelbCreateRuleApi ctelbCreateRuleApi;
    public final CtelbListAccessControlApi ctelbListAccessControlApi;
    public final CtelbUpdateAccessControlApi ctelbUpdateAccessControlApi;
    public final CtelbDeleteAccessControlApi ctelbDeleteAccessControlApi;
    public final CtelbCreateAccessControlApi ctelbCreateAccessControlApi;
    public final CtelbListCertificateApi ctelbListCertificateApi;
    public final CtelbShowCertificateApi ctelbShowCertificateApi;
    public final CtelbDeleteCertificateApi ctelbDeleteCertificateApi;
    public final CtelbCreateCertificateApi ctelbCreateCertificateApi;
    public final CtelbListHealthCheckApi ctelbListHealthCheckApi;
    public final CtelbUpdateHealthCheckApi ctelbUpdateHealthCheckApi;
    public final CtelbDeleteHealthCheckApi ctelbDeleteHealthCheckApi;
    public final CtelbCreateHealthCheckApi ctelbCreateHealthCheckApi;
    public final CtelbListTargetApi ctelbListTargetApi;
    public final CtelbShowTargetApi ctelbShowTargetApi;
    public final CtelbUpdateTargetApi ctelbUpdateTargetApi;
    public final CtelbDeleteTargetApi ctelbDeleteTargetApi;
    public final CtelbCreateTargetApi ctelbCreateTargetApi;
    public final CtelbListTargetGroupApi ctelbListTargetGroupApi;
    public final CtelbShowTargetGroupApi ctelbShowTargetGroupApi;
    public final CtelbDeleteTargetGroupApi ctelbDeleteTargetGroupApi;
    public final CtelbUpdateTargetGroupApi ctelbUpdateTargetGroupApi;
    public final CtelbCreateTargetGroupApi ctelbCreateTargetGroupApi;
    public final CtelbStopListenerApi ctelbStopListenerApi;
    public final CtelbStartListenerApi ctelbStartListenerApi;
    public final CtelbListListenerApi ctelbListListenerApi;
    public final CtelbShowListenerApi ctelbShowListenerApi;
    public final CtelbUpdateListenerApi ctelbUpdateListenerApi;
    public final CtelbDeleteListenerApi ctelbDeleteListenerApi;
    public final CtelbCreateListenerApi ctelbCreateListenerApi;
    public final CtelbDisassociateEipFromLoadBalancerApi ctelbDisassociateEipFromLoadBalancerApi;
    public final CtelbAssociateEipToLoadBalancerApi ctelbAssociateEipToLoadBalancerApi;
    public final CtelbListLoadBalancerApi ctelbListLoadBalancerApi;
    public final CtelbShowLoadBalancerApi ctelbShowLoadBalancerApi;
    public final CtelbUpdateLoadBalancerApi ctelbUpdateLoadBalancerApi;
    public final CtelbDeleteLoadBalancerApi ctelbDeleteLoadBalancerApi;
    public final CtelbCreateLoadBalancerApi ctelbCreateLoadBalancerApi;

    public Apis(String endpointUrl, CtyunClient ctyunClient) {
        ctyunClient.registerEndpoint(new Endpoint(ENDPOINT_NAME, endpointUrl));
        this.ctelbElbDisableIDCApi = new CtelbElbDisableIDCApi(ctyunClient);
        this.ctelbElbEnableIDCApi = new CtelbElbEnableIDCApi(ctyunClient);
        this.ctelbGwlbCreateApi = new CtelbGwlbCreateApi(ctyunClient);
        this.ctelbGwlbUpdateApi = new CtelbGwlbUpdateApi(ctyunClient);
        this.ctelbGwlbDeleteApi = new CtelbGwlbDeleteApi(ctyunClient);
        this.ctelbGwlbDisableDeleteProtectionApi =
                new CtelbGwlbDisableDeleteProtectionApi(ctyunClient);
        this.ctelbGwlbDisableIpv6Api = new CtelbGwlbDisableIpv6Api(ctyunClient);
        this.ctelbGwlbEnableIpv6Api = new CtelbGwlbEnableIpv6Api(ctyunClient);
        this.ctelbGwlbEnableDeleteProtectionApi =
                new CtelbGwlbEnableDeleteProtectionApi(ctyunClient);
        this.ctelbGwlbShowApi = new CtelbGwlbShowApi(ctyunClient);
        this.ctelbGwlbListApi = new CtelbGwlbListApi(ctyunClient);
        this.ctelbGwlbCreateTargetApi = new CtelbGwlbCreateTargetApi(ctyunClient);
        this.ctelbGwlbUpdateTargetApi = new CtelbGwlbUpdateTargetApi(ctyunClient);
        this.ctelbGwlbDeleteTargetApi = new CtelbGwlbDeleteTargetApi(ctyunClient);
        this.ctelbGwlbShowTargetApi = new CtelbGwlbShowTargetApi(ctyunClient);
        this.ctelbGwlbListTargetApi = new CtelbGwlbListTargetApi(ctyunClient);
        this.ctelbGwlbCreateTargetGroupApi = new CtelbGwlbCreateTargetGroupApi(ctyunClient);
        this.ctelbGwlbUpdateTargetGroupApi = new CtelbGwlbUpdateTargetGroupApi(ctyunClient);
        this.ctelbGwlbDeleteTargetGroupApi = new CtelbGwlbDeleteTargetGroupApi(ctyunClient);
        this.ctelbGwlbShowTargetGroupApi = new CtelbGwlbShowTargetGroupApi(ctyunClient);
        this.ctelbGwlbListTargetGroupApi = new CtelbGwlbListTargetGroupApi(ctyunClient);
        this.ctelbIplistenerCreateApi = new CtelbIplistenerCreateApi(ctyunClient);
        this.ctelbIplistenerUpdateApi = new CtelbIplistenerUpdateApi(ctyunClient);
        this.ctelbIplistenerDeleteApi = new CtelbIplistenerDeleteApi(ctyunClient);
        this.ctelbIplistenerShowApi = new CtelbIplistenerShowApi(ctyunClient);
        this.ctelbIplistenerListApi = new CtelbIplistenerListApi(ctyunClient);
        this.ctelbElbModifyAccessLogApi = new CtelbElbModifyAccessLogApi(ctyunClient);
        this.ctelbElbDeleteAccessLogApi = new CtelbElbDeleteAccessLogApi(ctyunClient);
        this.ctelbElbCreateAccessLogApi = new CtelbElbCreateAccessLogApi(ctyunClient);
        this.ctelbCheckServerCertApi = new CtelbCheckServerCertApi(ctyunClient);
        this.ctelbCheckCaCertApi = new CtelbCheckCaCertApi(ctyunClient);
        this.ctelbListDomainCertLinksApi = new CtelbListDomainCertLinksApi(ctyunClient);
        this.ctelbUpdateDomainCertLinksApi = new CtelbUpdateDomainCertLinksApi(ctyunClient);
        this.ctelbDeleteDomainCertLinksApi = new CtelbDeleteDomainCertLinksApi(ctyunClient);
        this.ctelbCreateDomainCertLinkApi = new CtelbCreateDomainCertLinkApi(ctyunClient);
        this.ctelbRefundPgelbApi = new CtelbRefundPgelbApi(ctyunClient);
        this.ctelbUpdateListenerResponseTimeoutApi =
                new CtelbUpdateListenerResponseTimeoutApi(ctyunClient);
        this.ctelbUpdateListenerQpsApi = new CtelbUpdateListenerQpsApi(ctyunClient);
        this.ctelbUpdateListenerNat64Api = new CtelbUpdateListenerNat64Api(ctyunClient);
        this.ctelbUpdateListenerIdleTimeoutApi = new CtelbUpdateListenerIdleTimeoutApi(ctyunClient);
        this.ctelbUpdateListenerEstabTimeoutApi =
                new CtelbUpdateListenerEstabTimeoutApi(ctyunClient);
        this.ctelbUpdateListenerCpsApi = new CtelbUpdateListenerCpsApi(ctyunClient);
        this.ctelbElbUnbindLabelsApi = new CtelbElbUnbindLabelsApi(ctyunClient);
        this.ctelbElbBindLabelsApi = new CtelbElbBindLabelsApi(ctyunClient);
        this.ctelbListElbLabelsApi = new CtelbListElbLabelsApi(ctyunClient);
        this.ctelbUpgradeToPgelbApi = new CtelbUpgradeToPgelbApi(ctyunClient);
        this.ctelbQueryRenewPgelbPriceApi = new CtelbQueryRenewPgelbPriceApi(ctyunClient);
        this.ctelbRenewPgelbApi = new CtelbRenewPgelbApi(ctyunClient);
        this.ctelbQueryModifyPgelbSpecPriceApi = new CtelbQueryModifyPgelbSpecPriceApi(ctyunClient);
        this.ctelbModifyPgelbSpecApi = new CtelbModifyPgelbSpecApi(ctyunClient);
        this.ctelbQueryCreatePgelbPriceApi = new CtelbQueryCreatePgelbPriceApi(ctyunClient);
        this.ctelbCreatePgelbApi = new CtelbCreatePgelbApi(ctyunClient);
        this.ctelbNewQueryElbReatimeMonitorApi = new CtelbNewQueryElbReatimeMonitorApi(ctyunClient);
        this.ctelbNewQueryElbHistoryMonitorApi = new CtelbNewQueryElbHistoryMonitorApi(ctyunClient);
        this.ctelbUpdateVmPoolAttrApi = new CtelbUpdateVmPoolAttrApi(ctyunClient);
        this.ctelbUpdatePolicyAttrApi = new CtelbUpdatePolicyAttrApi(ctyunClient);
        this.ctelbAsyncCreatePolicyApi = new CtelbAsyncCreatePolicyApi(ctyunClient);
        this.ctelbRemoveVmApi = new CtelbRemoveVmApi(ctyunClient);
        this.ctelbListVmApi = new CtelbListVmApi(ctyunClient);
        this.ctelbAsyncCreateTargetApi = new CtelbAsyncCreateTargetApi(ctyunClient);
        this.ctelbUpdateListenerAttrApi = new CtelbUpdateListenerAttrApi(ctyunClient);
        this.ctelbAsyncCreateListenerApi = new CtelbAsyncCreateListenerApi(ctyunClient);
        this.ctelbListVmPoolApi = new CtelbListVmPoolApi(ctyunClient);
        this.ctelbAsyncCreateCertificateApi = new CtelbAsyncCreateCertificateApi(ctyunClient);
        this.ctelbAsyncCreateLoadbalanceApi = new CtelbAsyncCreateLoadbalanceApi(ctyunClient);
        this.ctelbQueryElbHistoryMetricApi = new CtelbQueryElbHistoryMetricApi(ctyunClient);
        this.ctelbUpdateCertificateApi = new CtelbUpdateCertificateApi(ctyunClient);
        this.ctelbEnableElbIpv6Api = new CtelbEnableElbIpv6Api(ctyunClient);
        this.ctelbDisableElbIpv6Api = new CtelbDisableElbIpv6Api(ctyunClient);
        this.ctelbShowAccessControlApi = new CtelbShowAccessControlApi(ctyunClient);
        this.ctelbShowHealthCheckApi = new CtelbShowHealthCheckApi(ctyunClient);
        this.ctelbQueryElbReatimeMetricApi = new CtelbQueryElbReatimeMetricApi(ctyunClient);
        this.ctelbQuerySlaApi = new CtelbQuerySlaApi(ctyunClient);
        this.ctelbListQueryApi = new CtelbListQueryApi(ctyunClient);
        this.ctelbShowRuleApi = new CtelbShowRuleApi(ctyunClient);
        this.ctelbUpdateRuleApi = new CtelbUpdateRuleApi(ctyunClient);
        this.ctelbDeleteRuleApi = new CtelbDeleteRuleApi(ctyunClient);
        this.ctelbCreateRuleApi = new CtelbCreateRuleApi(ctyunClient);
        this.ctelbListAccessControlApi = new CtelbListAccessControlApi(ctyunClient);
        this.ctelbUpdateAccessControlApi = new CtelbUpdateAccessControlApi(ctyunClient);
        this.ctelbDeleteAccessControlApi = new CtelbDeleteAccessControlApi(ctyunClient);
        this.ctelbCreateAccessControlApi = new CtelbCreateAccessControlApi(ctyunClient);
        this.ctelbListCertificateApi = new CtelbListCertificateApi(ctyunClient);
        this.ctelbShowCertificateApi = new CtelbShowCertificateApi(ctyunClient);
        this.ctelbDeleteCertificateApi = new CtelbDeleteCertificateApi(ctyunClient);
        this.ctelbCreateCertificateApi = new CtelbCreateCertificateApi(ctyunClient);
        this.ctelbListHealthCheckApi = new CtelbListHealthCheckApi(ctyunClient);
        this.ctelbUpdateHealthCheckApi = new CtelbUpdateHealthCheckApi(ctyunClient);
        this.ctelbDeleteHealthCheckApi = new CtelbDeleteHealthCheckApi(ctyunClient);
        this.ctelbCreateHealthCheckApi = new CtelbCreateHealthCheckApi(ctyunClient);
        this.ctelbListTargetApi = new CtelbListTargetApi(ctyunClient);
        this.ctelbShowTargetApi = new CtelbShowTargetApi(ctyunClient);
        this.ctelbUpdateTargetApi = new CtelbUpdateTargetApi(ctyunClient);
        this.ctelbDeleteTargetApi = new CtelbDeleteTargetApi(ctyunClient);
        this.ctelbCreateTargetApi = new CtelbCreateTargetApi(ctyunClient);
        this.ctelbListTargetGroupApi = new CtelbListTargetGroupApi(ctyunClient);
        this.ctelbShowTargetGroupApi = new CtelbShowTargetGroupApi(ctyunClient);
        this.ctelbDeleteTargetGroupApi = new CtelbDeleteTargetGroupApi(ctyunClient);
        this.ctelbUpdateTargetGroupApi = new CtelbUpdateTargetGroupApi(ctyunClient);
        this.ctelbCreateTargetGroupApi = new CtelbCreateTargetGroupApi(ctyunClient);
        this.ctelbStopListenerApi = new CtelbStopListenerApi(ctyunClient);
        this.ctelbStartListenerApi = new CtelbStartListenerApi(ctyunClient);
        this.ctelbListListenerApi = new CtelbListListenerApi(ctyunClient);
        this.ctelbShowListenerApi = new CtelbShowListenerApi(ctyunClient);
        this.ctelbUpdateListenerApi = new CtelbUpdateListenerApi(ctyunClient);
        this.ctelbDeleteListenerApi = new CtelbDeleteListenerApi(ctyunClient);
        this.ctelbCreateListenerApi = new CtelbCreateListenerApi(ctyunClient);
        this.ctelbDisassociateEipFromLoadBalancerApi =
                new CtelbDisassociateEipFromLoadBalancerApi(ctyunClient);
        this.ctelbAssociateEipToLoadBalancerApi =
                new CtelbAssociateEipToLoadBalancerApi(ctyunClient);
        this.ctelbListLoadBalancerApi = new CtelbListLoadBalancerApi(ctyunClient);
        this.ctelbShowLoadBalancerApi = new CtelbShowLoadBalancerApi(ctyunClient);
        this.ctelbUpdateLoadBalancerApi = new CtelbUpdateLoadBalancerApi(ctyunClient);
        this.ctelbDeleteLoadBalancerApi = new CtelbDeleteLoadBalancerApi(ctyunClient);
        this.ctelbCreateLoadBalancerApi = new CtelbCreateLoadBalancerApi(ctyunClient);
    }
}
